### ISSUE TITLE
Advanced filtering

### ISSUE THREAD

**Issue by zaryana** [zaryana/star-wars-app#3]
The application should allow filtering the characters by multiple parameters (see [Wiki](https://github.com/zaryana/star-wars-app/wiki/Technical-Requirements) ).

**Comment by nzamosenchuk** [comment]
Star Wars characters can be filtered by the Films, Species, and Birth year.

<img width="1178" alt="screen shot 2018-03-07 at 22 06 49" src="https://user-images.githubusercontent.com/1624855/37118367-4bcf96e8-2254-11e8-99b3-98a227ebe1a2.png">

**Comment by zaryana** [comment]
Additional work is still needed and will be covered in #5 (UX part) and #6 (refactoring)
